config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :scanning_images
  resources :scannings
  resources :fish_slices
  resources :scanned_cells
  get 'fish-slice/:id/scannings', to: 'fish_slices#scannings', as: :scannings_from_fish_slice
  get 'exam/:id/slices', to: 'fish_slices#slices_from_exam', as: :slices_from_exam
  get 'scanning-images/processing', to: 'scanning_images#processing', as: :processing
  root to: 'home#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/fish_slice.rb
class FishSlice < ApplicationRecord
  include ResponsibleReference
  validates_presence_of :date, :probe, :genomico_exam_id
  has_one :exam
  accepts_nested_attributes_for :exam, allow_destroy: true
  paginates_per 10
  has_many :scannings
  enum probe: {
    bcr_abl: 1,
  }

  def self.probes_for_select
    probes.map do |probe, _|
      [ I18n.t("enums.fish_slice.probes.#{probe}"), probe ]
    end
  end

  def probe_name
    I18n.t("enums.fish_slice.probes.#{self.probe}")
  end

end

app/controllers/fish_slices_controller.rb
class FishSlicesController < ApplicationController
  helper_method :users

  def index
    @slices = FishSlice.includes(:exam).all.order(created_at: :desc).page params[:page]
  end

  def new
    @slice = FishSlice.new({genomico_exam_id: params[:exam_id], exam: Exam.new})
  end

  def create
    @slice = FishSlice.new slice_params
    if @slice.save
      flash[:success] = I18n.t :new_fish_slice_success
      redirect_to root_path
    else
      flash[:error] = @slice.errors.full_messages.first
      exam = @slice.exam
      redirect_to new_fish_slice_path(patient: exam.patient, name: exam.name, start_date: exam.start_date, subsample_label: exam.subsample_label, genomico_exam_id: exam.genomico_exam_id)
    end
  end

  def edit
  end

  def show
  end

  def slices_from_exam
    @slices = FishSlice.includes(:exam).where(genomico_exam_id: params[:id])
  end

  def scannings
    @scannings = FishSlice.find(params[:id]).scannings.includes(:fish_slice).order(date: :desc)
  end

  private

    def slice_params
      params.require(:fish_slice).permit(
        :genomico_exam_id,
        :responsible_id,
        :responsible_login,
        :date,
        :subsample_id,
        :subsample_label,
        :probe,
        exam_attributes: [:patient, :name, :start_date, :subsample_label, :genomico_exam_id]
      )
    end

    def exam_params
      {
        name: params[:name],
        patient: params[:patient],
        subsample_label: params[:subsample_label],
        start_date: params[:start_date]
      }
    end

end

app/views/fish_slices/edit.html.erb
<h1>Slices#edit</h1>
<p>Find me in app/views/slices/edit.html.erb</p>

app/views/fish_slices/index.html.erb
<%= render 'layouts/navbar' %>

<%= list_title "Lâminas" %>

<table>
  <thead>
    <th>Paciente</th>
    <th>Exame</th>
    <th>Data do preparo da lâmina</th>
    <th>Amostra</th>
    <th>Sonda</th>
    <th>Responsável</th>
    <th></th>
  </thead>
  <tbody>
    <% @slices.each do |slice| %>
      <tr class="fish-slice">
        <td><%= slice.exam.patient %></td>
        <td><%= slice.exam.name %></td>
        <td><%= l slice.date %></td>
        <td><%= slice.exam.subsample_label %></td>
        <td><%= slice.probe_name %></td>
        <td><%= slice.responsible_login %></td>
        <td>
          <%= link_to "Nova captura", new_scanning_path(slice_id: slice.id), class: 'btn btn-sm btn-outline-success new-scanning' %>
          <% unless slice.scannings.empty? %>
            <%= link_to "Capturas", scannings_from_fish_slice_path(slice), class: 'btn btn-sm btn-outline-info scannings-from-fish-slice'%>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= render 'layouts/table_footer', elements: @slices %>

app/views/fish_slices/new.html.erb
<%= render 'layouts/navbar' %>

<div class="form-card">
  <div class="card-header bg-primary">
    <h2>
      Nova lâmina
    </h2>
  </div>
  <div class="card-body">
    <%= form_with model: @slice, local: true do |form| %>
      <%= show_errors @slice %>
      <%= form.fields_for :exam_attributes do |exam_form| %>
        <%= exam_form.hidden_field :patient, value: params[:patient], class: 'form-control'%>
        <%= exam_form.hidden_field :name, value: params[:name], class: 'form-control' %>
        <%= exam_form.hidden_field :start_date, value: params[:start_date], class: 'form-control' %>
        <%= exam_form.hidden_field :subsample_label, value: params[:subsample_label], class: 'form-control' %>
        <%= exam_form.hidden_field :genomico_exam_id, value: params[:genomico_exam_id], class: 'form-control' %>
      <% end %>
      <%= form.hidden_field :genomico_exam_id, value: params[:genomico_exam_id] %>
      <div class="form-group">
        <%= form.label :responsible_id %>
        <%= form.select :responsible_id, options_from_collection_for_select(User.all, "id", "login"), {}, class: 'form-control' %>
        <%= form.text_field :responsible_login, hidden: true %>
      </div>
      <div class="form-group">
        <%= form.label :date %>
        <%= form.date_field :date, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :probe %>
        <%= form.select :probe, options_for_select(FishSlice.probes_for_select), {}, class: 'form-control' %>
      </div>
      <button id="btn-save" class="btn btn-outline-primary">
        Salvar
      </button>
    <% end %>
  </div>
</div>







<script>

  function set_user_login(){
    let responsible_select = $('#fish_slice_responsible_id')
    let selected_login = $('#fish_slice_responsible_id option:selected').text()
    $('#fish_slice_responsible_login').val(selected_login)
  }

  $(document).on('turbolinks:load', () => set_user_login())
  $('#fish_slice_responsible_id').on('change', () => set_user_login())

</script>

app/views/fish_slices/scannings.html.erb
<%= render 'layouts/navbar' %>

<%= list_title "Capturas" %>

<table>
  <thead>
    <th>Data</th>
    <th>Responsável</th>
    <th>Sonda</th>
    <th>Nucleos encontrados</th>
    <th>Imagens</th>
    <th></th>
  </thead>
  <tbody>
    <% @scannings.each do |scanning| %>
      <tr class="scanning">
        <td><%= l scanning.date %></td>
        <td><%= scanning.responsible_login %></td>
        <td><%= scanning.fish_slice.probe_name %></td>
        <td><%= scanning.valid_nucleus %></td>
        <td><%= scanning.scanning_images.size %></td>
        <td>
          <%= link_to "Captura", scanning %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/fish_slices/show.html.erb
<h1>Slices#show</h1>
<p>Find me in app/views/slices/show.html.erb</p>

app/views/fish_slices/slices_from_exam.html.erb
<%= render 'layouts/navbar' %>

<%= list_title "Lâminas de exame" %>

<table class="mt-5">
  <thead>
    <th>Responsável</th>
    <th>Data de preparo da lâmina</th>
    <th>Sonda</th>
    <th></th>
  </thead>
  <tbody>
    <% @slices.each do |slice| %>
      <tr class="slice">
        <td><%= slice.responsible_login %></td>
        <td><%= l slice.date %></td>
        <td><%= slice.probe_name %></td>
        <td>
          <%= link_to "Nova captura", new_scanning_path(slice_id: slice.id), class: 'btn btn-sm btn-outline-success new-scanning' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>