config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :scanning_images
  resources :scannings
  resources :fish_slices
  resources :scanned_cells
  get 'fish-slice/:id/scannings', to: 'fish_slices#scannings', as: :scannings_from_fish_slice
  get 'exam/:id/slices', to: 'fish_slices#slices_from_exam', as: :slices_from_exam
  get 'scanning-images/processing', to: 'scanning_images#processing', as: :processing
  root to: 'home#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/scanning_image.rb
class ScanningImage < ApplicationRecord
  belongs_to :scanning
  after_create_commit :extract_nucleus_job
  has_one_attached :original
  has_one_attached :marked
  has_many :scanned_cells
  before_validation :set_process_status
  after_update :check_if_all_imgaes_are_complete
  validates_with CheckOriginalImageValidator
  paginates_per 15
  enum process_status: {
    waiting_start: 1,
    marking_image: 2,
    extracting_nucleus: 3,
    complete: 4
  }
  before_validation :set_analysis_status
  enum analysis_status: {
    pending: 0,
    analyzed: 1
  }

  private

    def set_process_status
      self.process_status = :waiting_start unless self.process_status
    end

    def extract_nucleus_job
      ExtractNucleusJob.perform_later(self)
    end

    def check_if_all_imgaes_are_complete
      scanning = self.scanning
      scanning.update(process_status: :complete) unless scanning.scanning_images.size > scanning.scanning_images.complete.size
    end

    def set_analysis_status
      self.analysis_status = :pending unless self.analysis_status
    end

end

app/controllers/scanning_images_controller.rb
class ScanningImagesController < ApplicationController

  def index
    scanning_images = ScanningImage.complete
    if params[:status] == "pending"
      @scanning_images = scanning_images.pending.order(created_at: :desc).page params[:page]
    elsif params[:status] == "analyzed"
      @scanning_images = scanning_images.analyzed.order(created_at: :desc).page params[:page]
    elsif params[:status] == "processing"
      respond_to do |format|
        format.html
        format.json { render json: processing, status: :ok }
      end
    end
  end

  def show
    @scanned_cells = ScannedCell.where(scanning_image_id: params[:id]).order(:id).page params[:page]
  end

  def update
    @scanning_image = ScanningImage.find params[:id]
    if @scanning_image.update analysis_status: :analyzed
      flash[:success] = I18n.t :scanning_image_analyzed
    else
      flash[:error] = @scanning_image.errors.full_messages
    end
    redirect_to @scanning_image
  end

  private

  def processing
    images = ScanningImage.where.not(process_status: :complete).order(start_processing_at: :asc)
    images.map do |image|
      {
        id: image.id,
        start_processing_at: image.start_processing_at.strftime("%-d/%-m/%y: %H:%M:%S"),
        status: image.process_status
      }
    end
  end

end

app/helpers/scanning_images_helper.rb
module ScanningImagesHelper
end

app/views/scanning_images/_complete.html.erb
<h2 class="text-center mt-5">
  <%= params[:status] == "pending" ? "Imagens pendentes" : "Imagens já analisadas"%>
</h2>
<hr>

<table class="table-sm">
  <thead>
    <th>Imagem</th>
    <th>Exame</th>
    <th>Paciente</th>
    <th>Amostra</th>
    <th>Sonda</th>
    <th>Núcleos válidos</th>
    <th>Inicio do processamento</th>
    <th>Término do processamento</th>
    <th>Tempo de processamento</th>
    <th></th>
  </thead>
  <tbody>
    <% @scanning_images.each do |image| %>
      <tr class="scanning-image">
        <td><%= image.id %></td>
        <td><%= image.scanning.fish_slice.exam.name %></td>
        <td><%= image.scanning.fish_slice.exam.patient %></td>
        <td><%= image.scanning.fish_slice.exam.subsample_label %></td>
        <td><%= image.scanning.fish_slice.probe_name %></td>
        <td><%= image.valid_nucleus_found %></td>
        <td><%= l(image.start_processing_at) %></td>
        <td><%= l image.finish_processing_at %></td>
        <td><%= distance_of_time_in_words(image.finish_processing_at - image.start_processing_at) %></td>
        <td><%= link_to "Visualizar", image %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= render 'layouts/table_footer', elements: @scanning_images %>

app/views/scanning_images/_processing.html.erb
<div id="processing-elements">
  <h2 class="text-center mt-5">
    Imagens em processamento
  </h2>
  <hr>

  <table class="col-10 offset-1">
    <thead>
      <th>Imagem</th>
      <th>Iniciado em</th>
      <th class="col-2">Detectando núcleos</th>
      <th class="col-2">Extraindo núcleos</th>
    </thead>
    <tbody id="pending-images">
    </tbody>
  </table>
</div>

app/views/scanning_images/complete.html.erb
<%= render 'layouts/navbar' %>

<h2 class="text-center mt-5">
  Imagens processadas
</h2>
<hr>

<table class="table-sm">
  <thead>
    <th>Imagem</th>
    <th>Exame</th>
    <th>Paciente</th>
    <th>Amostra</th>
    <th>Sonda</th>
    <th>Núcleos válidos</th>
    <th>Inicio do processamento</th>
    <th>Término do processamento</th>
    <th>Tempo de processamento</th>
    <th></th>
  </thead>
  <tbody>
    <% @scanning_images.each do |image| %>
      <tr>
        <td><%= image.id %></td>
        <td><%= image.scanning.fish_slice.exam.name %></td>
        <td><%= image.scanning.fish_slice.exam.patient %></td>
        <td><%= image.scanning.fish_slice.exam.subsample_label %></td>
        <td><%= image.scanning.fish_slice.probe_name %></td>
        <td><%= image.valid_nucleus_found %></td>
        <td><%= l(image.start_processing_at) %></td>
        <td><%= l image.finish_processing_at %></td>
        <td><%= distance_of_time_in_words(image.finish_processing_at - image.start_processing_at) %></td>
        <td><%= link_to "Visualizar", image %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/scanning_images/index.html.erb
<%= render 'layouts/navbar' %>

<% unless params[:status] == "processing" %>
  <%= render 'complete' %>
<% else %>
  <%= render 'processing' %>
<% end %>

app/views/scanning_images/pending_analysis.html.erb
<%= render 'layouts/navbar' %>

<h2 class="text-center mt-5">
  Imagens processadas
</h2>
<hr>

<table class="table-sm">
  <thead>
    <th>Imagem</th>
    <th>Exame</th>
    <th>Paciente</th>
    <th>Amostra</th>
    <th>Sonda</th>
    <th>Núcleos válidos</th>
    <th>Inicio do processamento</th>
    <th>Término do processamento</th>
    <th>Tempo de processamento</th>
    <th></th>
  </thead>
  <tbody>
    <% @scanning_images.each do |image| %>
      <tr>
        <td><%= image.id %></td>
        <td><%= image.scanning.fish_slice.exam.name %></td>
        <td><%= image.scanning.fish_slice.exam.patient %></td>
        <td><%= image.scanning.fish_slice.exam.subsample_label %></td>
        <td><%= image.scanning.fish_slice.probe_name %></td>
        <td><%= image.valid_nucleus_found %></td>
        <td><%= l(image.start_processing_at) %></td>
        <td><%= l image.finish_processing_at %></td>
        <td><%= distance_of_time_in_words(image.finish_processing_at - image.start_processing_at) %></td>
        <td><%= link_to "Visualizar", image %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/scanning_images/show.html.erb
<%= render 'layouts/navbar' %>

<div id="single-nucleus-card" class="card col-4 p-0 offset-4" style="display: none;">
  <div class="card-header">
    <span id="channel-paths" hidden></span>
    <span id="nucleus-label" hidden></span>
    <span id="nucleus-id" hidden></span>
    <button id="blue-channel" class="btn btn-primary with-blue">Azul</button>
    <button id="green-channel" class="btn btn-success with-green">Verde</button>
    <button id="red-channel" class="btn btn-danger with-red">Vermelho</button>
    <button id="mark-as-appropriate" class="btn btn-outline-success ml-5">Marcar como adequada</button>
    <button id="mark-as-inappropriate" class="btn btn-outline-danger ml-5">Marcar como inadequada</button>
    <button id="treated" class="btn btn-outline-dark float-right">Tratar</button>
    <button id="original" class="btn btn-outline-info float-right" hidden>Original</button>
  </div>
  <div class="card-body">
    <img id="single-nucleus" src="" class="col-12">
  </div>
</div>

<div id="shade" style="position: absolute; top: 0px; left: 0px; right: 0px; background-color: rgba(0, 0, 0, 0.7); z-index: 2; display: none;">
</div>


<div class="p-5" style="background-color: rgba(0, 0, 0, .65)">
  <% scanning_image = @scanned_cells.first.scanning_image %>
  <% if scanning_image.pending? %>
    <div class="pb-3">
      <%= link_to "Analizada", scanning_image_path(scanning_image), class: 'btn btn-lg btn-outline-primary offset-10 analyze-image', method: :patch %>
    </div>
  <% else %>
    <h4 id='processing-image-status' class="text-center pb-3 text-white">
      Imagem já analizada
    </h4>
    <hr>
  <% end %>
  <% @scanned_cells.each do |cell| %>
    <div id="cell-<%= cell.id %>" class="card d-inline-block <%= cell.appropriate? ? "appropriate" : "inappropriate" %>" style="margin-left: 15px; margin-bottom: 15px; margin-right: 15px; border: 3px solid <%= cell.appropriate? ? "rgb(40, 167, 69);" : "rgb(202, 37, 53);" %>">
      <%= image_tag cell.rgb, class: "cell", style: {width: 125, height: 125}, data_value: cell.id, data_label: cell.analysis_label %>
    </div>
  <% end %>
  <%= render 'layouts/table_footer', elements: @scanned_cells %>
</div>