config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :scanning_images
  resources :scannings
  resources :fish_slices
  resources :scanned_cells
  get 'fish-slice/:id/scannings', to: 'fish_slices#scannings', as: :scannings_from_fish_slice
  get 'exam/:id/slices', to: 'fish_slices#slices_from_exam', as: :slices_from_exam
  get 'scanning-images/processing', to: 'scanning_images#processing', as: :processing
  root to: 'home#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    begin
      response = RestClient.get('cda0015.cdapp.net.br:3000/fish-api/exams')
    rescue
      response = {}.to_json
    end
    @exams = JSON.parse(response).map do |exam|
      GenomicoExamPresenter.new({
        exam: exam["exam"],
        patient: exam["patient"],
        subsample_label: exam["subsample_label"],
        started_at: exam["started_at"],
        status: exam["status"],
        sample_id: exam["sample_id"],
        subsample_label: exam["subsample_label"],
        id: exam["id"]
      })
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_status_table.html.erb
<div id="processing-elements">
  <h2 class="text-center mt-5">
    Imagens em processamento
  </h2>
  <hr>

  <table class="col-10 offset-1">
    <thead>
      <th>Imagem</th>
      <th>Iniciado em</th>
      <th class="col-2">Detectando núcleos</th>
      <th class="col-2">Extraindo núcleos</th>
      <th class="col-2">Processando núcleos</th>
    </thead>
    <tbody id="pending-images">
    </tbody>
  </table>
</div>

<script>

  function marking_image(status){
    if (status === "marking_image"){
      return "Processando";
    }else if ( status === 'extracting_nucleus' || status === "processing_nucleus"){
      return "<span class='text-primary'>Concluído</span>";
    }
  }

  function extracting_nucleus(status){
    if (status === "extracting_nucleus"){
      return "Processando";
    } else if (status === "processing_nucleus"){
      return "<span class='text-info'>Concluído</span>";
    }else{
      return "";
    }
  }

  function processing_nucleus(status){
    if (status === "processing_nucleus"){
      return "Processando";
    }else{
      return "";
    }
  }

  function line_builder(processing_image){
    $("#pending-images").append(`
      <tr id="${processing_image.id}-image" class="processing-image">
        <td>${processing_image.id}</td>
        <td>${processing_image.start_processing_at}</td>
        <td class="marking_image">${marking_image(processing_image.status)}</td>
        <td class="extracting_nucleus">${extracting_nucleus(processing_image.status)}</td>
        <td class="processing_nucleus">${processing_nucleus(processing_image.status)}</td>
      </tr>
      `).hide().fadeIn(800)
    return $(`#${processing_image.id}-image`)
  }

  function remove_complete_lines(updated_lines){
    let updated_ids = updated_lines.map(line => line.id );
    let keys = Object.keys(virtual_table);
    let displayed_elements = keys.map(key => virtual_table[key]);
    displayed_elements.forEach(element => {
      if (updated_ids.includes(element.id) === false){
        element.dom.fadeOut(800);
      }
    })
  }

  function check_lines(updated_lines){
    remove_complete_lines(updated_lines);
    updated_lines.forEach(line => {
      let keys = Object.keys(virtual_table);
      if (keys.includes(line.id.toString()) === false){
        let dom_element = line_builder(line);
        let element = {
          id: line.id,
          dom: dom_element,
          current_status: line.status
        }
        virtual_table[line.id.toString()] = element;
      } else {
        let virtual_image = virtual_table[line.id.toString()];
        if (virtual_image.current_status !== line.status) {
          if (line.status === "extracting_nucleus"){
            let previous = virtual_image.dom.children('.marking_image')
            previous.text("")
            previous.append(`<span class="text-primary">Concluído</span>`)
            let cell = virtual_image.dom.children('.extracting_nucleus')
          } else if (line.status === 'processing_nucleus') {
            let previous_cell = virtual_image.dom.children('.extracting_nucleus').first();
            previous_cell.text("");
            previous_cell.append("<span class='text-info'>Concluído</span>");
            let cell = virtual_image.dom.children('.processing_nucleus');
            cell.text("Processando");
          }
          virtual_table[line.id.toString()].current_status = line.status;
        }
      }
    })
  }

  function reload_processing_table(){
    $.ajax({
      url: '/scanning-images/processing',
      success: (response) => {
        if (response.length === 0)
          $("#processing-elements").hide()
        else{
          $("#processing-elements").show()
          check_lines(response);
        }
      },
      error: (error) => {
        console.log("Erro ao obter dados do servidor.");
      }
    });
  }

  var virtual_table = {};

  $(document).on('turbolinks:load', () => {
    setInterval(reload_processing_table, 5000);
  });
</script>

app/views/home/index.html.erb
<%= render 'layouts/navbar' %>

<h2 class="text-center mt-3">
  Exames em andamento
</h2>

<hr>

<table>
  <thead class="bg-secondary">
    <th>Exame</th>
    <th>Paciente</th>
    <th>Amostra</th>
    <th>Iniciado em</th>
    <th>Status</th>
    <th></th>
  </thead>
  <tbody>
    <% @exams.each do |exam| %>
      <tr class="exam">
        <td><%= exam.exam %></td>
        <td><%= exam.patient %></td>
        <td><%= exam.subsample_label %></td>
        <td><%= exam.started_at %></td>
        <td><%= exam.status %></td>
        <td>
          <%= link_to "Nova lâmina", new_fish_slice_path(exam_id: exam.id, name: exam.exam, patient: exam.patient, subsample_label: exam.subsample_label, start_date: exam.started_at, genomico_exam_id: exam.id), class: 'btn btn-sm btn-outline-info new-slice' %>
          <% unless FishSlice.where(genomico_exam_id: exam.id).empty? %>
            <%= link_to "Lâminas", slices_from_exam_path(exam.id), class: 'btn btn-sm btn-outline-secondary slices-from-exam' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>