config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :scanning_images
  resources :scannings
  resources :fish_slices
  resources :scanned_cells
  get 'fish-slice/:id/scannings', to: 'fish_slices#scannings', as: :scannings_from_fish_slice
  get 'exam/:id/slices', to: 'fish_slices#slices_from_exam', as: :slices_from_exam
  get 'scanning-images/processing', to: 'scanning_images#processing', as: :processing
  root to: 'home#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #563d7c;">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <span class="fa fa-fish text-danger" style="font-weight: 900;"></span>
    <span class='text-primary'>FISH</span>
    <span class="fa fa-fish text-success"></span>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= link_to "Lâminas", fish_slices_path, class: 'nav-link fish-slices' %>
      <%= link_to "Processando", scanning_images_path(status: 'processing'), class: 'nav-link processing-images' %>
      <%= link_to "Imagens para análise", scanning_images_path(status: "pending"), class: 'nav-link', id: 'pending-analysis-images' %>
      <%= link_to "Imagens analizadas", scanning_images_path(status: 'analyzed'), class: 'nav-link', id: 'analyzed-images' %>
    </ul>
  </div>
</nav>

<% if flash[:success] %>
  <div class="alert alert-success" role="alert" id = 'success-message'>
    <%= flash[:success] %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-danger" role = 'alert' id = 'error-message'>
    <%= flash[:error] %>
  </div>
<% end %>

app/views/layouts/_table_footer.html.erb
<div id="pagination" class="container pagination justify-content-center" >
  <%= paginate elements , theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FishModuleGenomico</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>